### ISSUE TITLE
Overreaching ?ops regex

### ISSUE THREAD

**Issue by linuxdaemon** [CasualConversation/casualbotler#1]
https://github.com/CasualConversation/casualbotler/blob/ba8ed0f437ebc793b65077ddb4a9f0c28cc9c40e/modules/reme.py#L86
This regex would currently match `?opsarebutts` as well as `?ops`, something like `\?ops(\s.*|$) may be better as it would avoid false matches.

**Comment by znuxor** [comment]
should be fixed with https://github.com/CasualConversation/casualbotler/commit/a37c36e28696ddf3ed0ad5ff198983baedc0e692
