### ISSUE TITLE
Shreddit isn't recognized as a bot in #talk for banlogger.

### ISSUE THREAD

**Issue by znuxor** [CasualConversation/casualbotler#2]

**Comment by linuxdaemon** [comment]
Seems to be an issue on https://github.com/CasualConversation/casualbotler/blob/14f94ba8e51a5c30ab292c9a2e8dd4cacf2d1807/modules/banlogger.py#L124 and https://github.com/CasualConversation/casualbotler/blob/14f94ba8e51a5c30ab292c9a2e8dd4cacf2d1807/modules/banlogger.py#L140

Might be helpful to write a function to determine if the action was performed by a services bot. I can make a quick PR to add the logic if you want

**Comment by linuxdaemon** [comment]
The issue also affects:
- `#casualnsfw` (NSA)
- `#casualappeals` (ChanServ)

**Comment by znuxor** [comment]
Fixed in commit 43fa0a0ce9141ae6c3c858c35ba96956288112f3 . Thanks for the suggestion!
